version: "3"

services:
  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: cgrates_web_jsonapi_dev
      MYSQL_USER: cgrates
      MYSQL_PASSWORD: cgrates

  cgrates_web_jsonapi:
    image: maxkonin/cgrates_web_jsonapi
    container_name: cgrates_web_jsonapi
    depends_on:
      - db
    ports:
      - "4000:8000"
    environment:
      HOST: localhost
      SECRET_KEY_BASE: FdhoVLqowHllh1dfJw2Pk3LG9QZLFYmdY1Wffsca6Q1IkMFfNhtUTTzGTaP5umMT
      GUARDIAN_SECRET_KEY: 1LT/1JSIfn/lz04cYyAOh/g3w2rMkho7AF1rURe5/mvyFY25e+2TzxOBCCUWeS7w
      MYSQL_USER: cgrates
      MYSQL_PASSWORD: cgrates
      MYSQL_HOST: db
      MYSQL_DATABASE: cgrates_web_jsonapi_dev
      CGRATES_URL: cgrate.example.com
      CGRATES_TENANT: cgrates.org
      CGRATES_USERNAME: username
      CGRATES_PASSWORD: password
